name: NGA Daily Report

on:
  schedule:
    - cron: '0 14 * * *'  # 每天北京时间22:00运行
  workflow_dispatch:  # 允许手动触发

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'pip'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run daily report
      env:
        SMTP_SERVER: smtp.qq.com
        SMTP_PORT: 587
        SENDER_EMAIL: 360773337@qq.com
        RECIPIENT_EMAIL: 360773337@qq.com
        SENDER_PASSWORD: ${{ secrets.QQ_EMAIL_PASSWORD }}
      run: |
        python nga_daily_report.py
    
    - name: Upload report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: nga-daily-report
        path: |
          *.html
          *.log
        retention-days: 7
