# 使用pip而不是conda的GitHub Actions工作流

name: NGA Daily Report Pipeline

on:
  schedule:
    - cron: '0 14 * * *'  # 每天北京时间22:00运行
  workflow_dispatch:  # 允许手动触发
  push:  # 推送代码时触发
    branches: [ main ]
  pull_request:  # PR时触发
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10"]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Test script syntax
      run: |
        python -m py_compile nga_daily_report.py
        python -m py_compile test_local.py
    
    - name: Run daily report
      env:
        SMTP_SERVER: smtp.qq.com
        SMTP_PORT: 587
        SENDER_EMAIL: 360773337@qq.com
        RECIPIENT_EMAIL: 360773337@qq.com
        SENDER_PASSWORD: ${{ secrets.QQ_EMAIL_PASSWORD }}
      run: |
        python nga_daily_report.py
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: nga-daily-report-${{ github.run_number }}
        path: |
          *.html
          *.log
        retention-days: 7